name: Build and test frontend

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      ref:
        required: false
        type: string

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "version = ${{ inputs.version }}"
      - run: echo "ref = ${{ inputs.ref }}"
