name: Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
    debug:
      runs-on: ubuntu-latest
      steps:
        - run: echo "version = ${{ inputs.version }}"
        - run: echo "environment = ${{ inputs.environment }}"
    deploy1:
      runs-on: ubuntu-latest
      steps:
        - run: echo "version = ${{ inputs.version }}"
        - run: echo "environment = ${{ inputs.environment }}"
    deploy2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "version = ${{ inputs.version }}"
        - run: echo "environment = ${{ inputs.environment }}"
