name: Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      requires_approval:
        required: true
        type: boolean

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "version = ${{ inputs.version }}"
      - run: echo "requires_approval = ${{ inputs.requires_approval }}"
