name: Create new version (package.json & CHANGELOG)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-new-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create version & update CHANGELOG
        id: tag
        run: |
          git config --global user.email "botexample.com"
          git config --global user.name "Mr. Bot"
          VERSION=$(npm version ${{ inputs.version }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Push
        run: git push origin main --tags

        
  build:
    needs: [create-new-version]
    uses: ifrost/deployme2/.github/workflows/build.yml@main
    with:
      version: ${{ needs.create-new-version.outputs.version }}
      ref: ${{ needs.create-new-version.outputs.version }}

  package:
    needs: [build]
    uses: ifrost/deployme2/.github/workflows/package.yml@main
    secrets: inherit
    with:
      version: ${{ needs.create-new-version.outputs.version }}
      requires_approval: true

  deploy:
    needs: [create-new-version, package]
    uses: ifrost/deployme2/.github/workflows/deploy.yml@main
    secrets: inherit
    strategy:
      matrix:
        environment: [dev, ops, prod]
    with:
      version: ${{ needs.create-new-version.outputs.version }}
      environment: ${{ matrix.environment }}
